# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo-BDD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo-BDD

  target 'demo-BDDTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble'
    pod 'Quick'	
  end

  target 'demo-BDDUITests' do
    # Pods for testing
  end

end
