// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "demo",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "demo",
            targets: ["AppModule"],
            bundleIdentifier: "utopios.demo",
            teamIdentifier: "6ZXF9YPHX7",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .movieReel),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/ReactiveX/RxSwift", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "RxCocoa", package: "rxswift"),
                .product(name: "RxSwift", package: "rxswift")
            ],
            path: "."
        )
    ]
)